[tool.black]
line-length = 120
target-version = ['py310', 'py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs         # exclude directories
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 120
